export const ANNOTATION_ACTIONS = {
  UPDATE_TOOL_INSTANCE: '@@UPDATE_TOOL_INSTANCE',
  UPDATE_IMG_LIST: '@@UPDATE_IMG_LIST',
  UPDATE_ANNOTATION_CONFIG: '@@UPDATE_ANNOTATION_CONFIG',
  PAGE_BACKWARD: '@@PAGE_BACKWARD',
  PAGE_FORWARD: '@@PAGE_FORWARD',
  PAGE_JUMP: '@@PAGE_JUMP',
  LOAD_FILE_DATA: '@@LOAD_FILE_DATA',
  SUBMIT_FILE_DATA: '@@SUBMIT_FILE_DATA',
  SET_TASK_CONFIG: '@@SET_TASK_CONFIG',
  INIT_TOOL: '@@INIT_TOOL',
  UPDATE_ON_SUBMIT: '@@UPDATE_ON_SUBMIT',
  UPDATE_ROTATE: '@@UPDATE_ROTATE',
  UPDATE_GET_FILE_DATA: '@@UPDATE_GET_FILE_DATA',
  GET_FILE_DATA: '@@GET_FILE_DATA',
  SET_FILE_DATA: '@@SET_FILE_DATA',
  COPY_BACKWARD_RESULT: '@@COPY_BACKWARD_RESULT'
};

export const IMAGE_ATTRIBUTE_ACTIONS = {
  UPDATE_IMG_ATTRIBUTE: '@@UPDATE_IMG_ATTRIBUTE',
  INIT_IMG_ATTRIBUTE: '@@INIT_IMG_ATTRIBUTE',
};

export const TOOL_STYLE_ACTIONS = {
  INIT_TOOL_STYLE_CONFIG: '@@INIT_TOOL_STYLE_CONFIG',
  UPDATE_TOOL_STYLE_CONFIG: '@@UPDATE_TOOL_STYLE_CONFIG',
};
